
=pod

=head1 Changes in ZedLog

=head2 v0.2beta3 - Released-July-2013 

=over 4

=item * Added command line interface.

=item * Fixed deadlock problem in shutdown sequence.

=item * Fixed run scripts.

=back

=head2 v0.2beta2 - Released 12-July-2013

=over 4

=item * Removed GUI Builder dependancy.

=item * General code cleanup/refactoring.

=item * Updated embedded program documentation.

=back

=head2 v0.2beta - Released 13-May-2013

=over 4

=item * Added initial replay simulation tool.

=item * Saving and opening log files.

=item * Added record/pause button.

=item * Separate mouse pressed & released loggers.

=item * More polished GUI and a new icon set.

=back

=head2 v0.1beta - Released 2-May-2013

Initial version.

=head2 Author

 Zachary Scott <zscott.dev@gmail.com>

=cut
